# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b75247d37aa32885023d537d004f8f59a187b85c1bbb5a09562740b2625c5cc2dcdb8ee8aed61449f3bb68a2dde69c25c1f72ec660fe1830016272d76c46f29

test:
  secret_key_base: b31632436e1e93c38dadea4a8a909575a511e1cf29712d692dda1488c1d522eea1cbf2f4feab2f67be04cd5bd14ce57ccebfe637fcbce51fcbc88a5b02dddd01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
